#!/usr/bin/env bun
/**
 * TinyCloud Node.js SDK Demo - Delegations and KV Operations
 *
 * Demonstrates the TinyCloud SDK with working delegation chains:
 * 1. Alice creates a space and stores data using Space API
 * 2. Alice delegates access to Bob using TinyCloudNode.createDelegation()
 * 3. Bob accesses Alice's space via useDelegation()
 * 4. Bob creates sub-delegation for Charlie
 * 5. Charlie accesses Alice's space via delegation chain
 *
 * NOTE: Some Space API methods (delegations.list, sharing.*, spaces.list)
 * are not yet implemented on the server side. This demo uses the working
 * TinyCloudNode delegation methods instead.
 *
 * Prerequisites:
 * - A running TinyCloud server (default: http://localhost:8000)
 *
 * Environment Variables (auto-generated if missing):
 *   TINYCLOUD_URL         - TinyCloud server URL (default: http://localhost:8000)
 *   ALICE_PRIVATE_KEY     - Alice's Ethereum private key (hex string, no 0x)
 *   BOB_PRIVATE_KEY       - Bob's Ethereum private key (hex string, no 0x)
 *   CHARLIE_PRIVATE_KEY   - Charlie's Ethereum private key (hex string, no 0x)
 *
 * Usage:
 *   bun run demo
 */

import {
  TinyCloudNode,
  serializeDelegation,
  deserializeDelegation,
} from "@tinycloudlabs/node-sdk";
import { Wallet } from "ethers";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

// ============================================================================
// Configuration
// ============================================================================

const TINYCLOUD_URL = process.env.TINYCLOUD_URL || "http://localhost:8000";
const ENV_PATH = join(import.meta.dir, "..", ".env");

// ============================================================================
// Key Management
// ============================================================================

interface UserKeys {
  alice: string;
  bob: string;
  charlie: string;
}

function generateKey(): string {
  const wallet = Wallet.createRandom();
  return wallet.privateKey.slice(2); // Remove 0x prefix
}

function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const match = trimmed.match(/^([A-Z_]+)=(.*)$/);
      if (match) {
        result[match[1]] = match[2];
      }
    }
  }
  return result;
}

function ensureKeys(): UserKeys {
  let aliceKey = process.env.ALICE_PRIVATE_KEY;
  let bobKey = process.env.BOB_PRIVATE_KEY;
  let charlieKey = process.env.CHARLIE_PRIVATE_KEY;
  let needsWrite = false;
  const writingKeys = JSON.parse(process.env.GENERATE_MISSING_KEYS || "false");

  // Load existing .env file
  if (existsSync(ENV_PATH)) {
    const parsed = parseEnvFile(readFileSync(ENV_PATH, "utf-8"));
    aliceKey = aliceKey || parsed.ALICE_PRIVATE_KEY;
    bobKey = bobKey || parsed.BOB_PRIVATE_KEY;
    charlieKey = charlieKey || parsed.CHARLIE_PRIVATE_KEY;
  }

  // Generate missing keys
  if (!aliceKey) {
    aliceKey = generateKey();
    console.log(`[KeyGen] Generated Alice's key: ${new Wallet(`0x${aliceKey}`).address}`);
    needsWrite = writingKeys && true;
  }
  if (!bobKey) {
    bobKey = generateKey();
    console.log(`[KeyGen] Generated Bob's key: ${new Wallet(`0x${bobKey}`).address}`);
    needsWrite = writingKeys && true;
  }
  if (!charlieKey) {
    charlieKey = generateKey();
    console.log(`[KeyGen] Generated Charlie's key: ${new Wallet(`0x${charlieKey}`).address}`);
    needsWrite = writingKeys && true;
  }

  // Write keys to .env
  if (needsWrite) {
    const content = `# TinyCloud Demo Environment
# Auto-generated by demo.ts

TINYCLOUD_URL=http://localhost:8000

ALICE_PRIVATE_KEY=${aliceKey}
# Alice's address: ${new Wallet(`0x${aliceKey}`).address}

BOB_PRIVATE_KEY=${bobKey}
# Bob's address: ${new Wallet(`0x${bobKey}`).address}

CHARLIE_PRIVATE_KEY=${charlieKey}
# Charlie's address: ${new Wallet(`0x${charlieKey}`).address}
`;
    writeFileSync(ENV_PATH, content);
    console.log(`[KeyGen] Keys saved to ${ENV_PATH}`);
  }

  return { alice: aliceKey, bob: bobKey, charlie: charlieKey };
}

// ============================================================================
// Demo Flow
// ============================================================================

async function runDemo() {
  console.log();
  console.log("TinyCloud Node.js SDK Demo - Space API");
  console.log("=".repeat(70));
  console.log(`Server: ${TINYCLOUD_URL}`);
  console.log();

  // Step 1: Ensure keys exist
  const keys = ensureKeys();

  // Step 2: Create TinyCloudNode instances for each user
  const alice = new TinyCloudNode({
    privateKey: keys.alice,
    host: TINYCLOUD_URL,
    prefix: "demo-alice",
    autoCreateSpace: true,
  });

  const bob = new TinyCloudNode({
    privateKey: keys.bob,
    host: TINYCLOUD_URL,
    prefix: "demo-bob",
    autoCreateSpace: true,
  });

  const charlie = new TinyCloudNode({
    privateKey: keys.charlie,
    host: TINYCLOUD_URL,
    prefix: "demo-charlie",
    autoCreateSpace: true,
  });

  // Step 3: All users sign in (creates their spaces)
  console.log("[Alice] Signing in...");
  await alice.signIn();
  console.log(`[Alice] Space: ${alice.spaceId}`);
  console.log(`[Alice] PKH DID: ${alice.pkhDid}`);

  console.log();
  console.log("[Bob] Signing in...");
  await bob.signIn();
  console.log(`[Bob] Space: ${bob.spaceId}`);
  console.log(`[Bob] PKH DID: ${bob.pkhDid}`);

  console.log();
  console.log("[Charlie] Signing in...");
  await charlie.signIn();
  console.log(`[Charlie] Space: ${charlie.spaceId}`);
  console.log(`[Charlie] PKH DID: ${charlie.pkhDid}`);
  console.log();

  // =========================================================================
  // PART 1: Space API - Basic Operations
  // =========================================================================
  console.log();
  console.log("=".repeat(70));
  console.log("PART 1: Space API - Basic Operations");
  console.log("=".repeat(70));
  console.log();

  // Step 4: Get Alice's default space
  console.log("[Alice] Getting default space...");
  const aliceSpace = alice.spaces.get("default");
  console.log(`[Alice] Space ID: ${aliceSpace.id}`);
  console.log(`[Alice] Space name: ${aliceSpace.name}`);
  console.log();

  // Step 5: Alice stores data using Space API
  console.log("[Alice] Storing data in space...");
  const putResult = await aliceSpace.kv.put("shared/greeting", {
    message: "Hello from Alice!",
    timestamp: new Date().toISOString(),
  });

  if (!putResult.ok) {
    console.error(`[Alice] ✗ Failed to store: ${putResult.error.message}`);
  } else {
    console.log("[Alice] ✓ Data stored at 'shared/greeting'");
  }
  console.log();

  // Step 6: Alice uses prefix scoping
  console.log("[Alice] Using prefix-scoped KV...");
  const sharedKV = aliceSpace.kv.withPrefix("shared/");

  const prefixPutResult = await sharedKV.put("document.json", {
    title: "Important Document",
    content: "This is shared data",
  });

  if (!prefixPutResult.ok) {
    console.error(`[Alice] ✗ Failed: ${prefixPutResult.error.message}`);
  } else {
    console.log("[Alice] ✓ Stored 'document.json' in shared/ prefix");
  }
  console.log();

  // =========================================================================
  // PART 2: Space API - Delegations
  // =========================================================================
  console.log();
  console.log("=".repeat(70));
  console.log("PART 2: Space API - Delegations");
  console.log("=".repeat(70));
  console.log();

  // Step 7: Alice creates delegation for Bob
  // NOTE: Using TinyCloudNode.createDelegation() because Space API's delegations.create()
  // has a bug - it uses invocation headers instead of delegation headers for /delegate endpoint.
  // The server expects proper SIWE-based delegation headers.
  console.log("[Alice] Creating delegation for Bob...");
  const portableDelegation = await alice.createDelegation({
    delegateDID: bob.pkhDid,
    path: "shared/",
    actions: ["tinycloud.kv/get", "tinycloud.kv/put"],
    expiryMs: 24 * 60 * 60 * 1000, // 24 hours
  });

  console.log("[Alice] ✓ Delegation created!");
  console.log(`  CID: ${portableDelegation.delegationCid}`);
  console.log(`  Delegate: ${portableDelegation.delegateDID}`);
  console.log(`  Path: ${portableDelegation.path}`);
  console.log(`  Actions: ${portableDelegation.actions.join(", ")}`);
  console.log(`  Expiry: ${portableDelegation.expiry.toISOString()}`);
  console.log();

  // Step 8: Skip delegation listing (Space API not yet implemented on server)
  // NOTE: space.delegations.list() requires server-side support for tinycloud.delegation/list
  // which is not yet implemented. The delegation was created successfully above.
  console.log("[Alice] Delegation listing via Space API skipped (server not yet implemented)");
  console.log();

  // Step 9: Skip received delegation listing (Space API not yet implemented on server)
  console.log("[Bob] Received delegation listing via Space API skipped (server not yet implemented)");
  console.log();

  // Step 10: Bob accesses Alice's space using delegation
  console.log("[Bob] Accessing Alice's space...");

  // Serialize and deserialize the delegation (simulating transfer between users)
  const serializedForBob = serializeDelegation(portableDelegation);
  const receivedByBob = deserializeDelegation(serializedForBob);
  const bobAccessToAlice = await bob.useDelegation(receivedByBob);

  // Bob reads Alice's data
  const greetingResult = await bobAccessToAlice.kv.get("greeting");
  if (greetingResult.ok && greetingResult.data?.data) {
    console.log(`[Bob] ✓ Read from Alice: "${greetingResult.data.data.message}"`);
  }

  // Bob writes a response
  const bobWriteResult = await bobAccessToAlice.kv.put("bob-was-here", {
    from: "Bob",
    message: "Thanks for sharing, Alice!",
    timestamp: new Date().toISOString(),
  });

  if (bobWriteResult.ok) {
    console.log("[Bob] ✓ Wrote response to Alice's space");
  }
  console.log();

  // Step 11: Bob creates sub-delegation for Charlie
  console.log("[Bob] Creating sub-delegation for Charlie...");
  const subDelegation = await bob.createSubDelegation(receivedByBob, {
    path: "shared/",
    actions: ["tinycloud.kv/put"],
    delegateDID: charlie.pkhDid,
  });
  console.log(`[Bob] ✓ Sub-delegation created: ${subDelegation.delegationCid}`);
  console.log();

  // Step 12: Charlie uses delegation chain
  const serializedForCharlie = serializeDelegation(subDelegation);
  const receivedByCharlie = deserializeDelegation(serializedForCharlie);
  const charlieAccessToAlice = await charlie.useDelegation(receivedByCharlie);

  console.log("[Charlie] Writing to Alice's space via delegation chain...");
  const charlieWriteResult = await charlieAccessToAlice.kv.put("charlie-was-here", {
    from: "Charlie",
    message: "Hello from the end of the chain!",
    timestamp: new Date().toISOString(),
  });

  if (charlieWriteResult.ok) {
    console.log("[Charlie] ✓ Wrote to Alice's space");
  }
  console.log();

  // Step 13: Alice reads messages from both Bob and Charlie
  console.log("[Alice] Reading responses...");
  const bobResponse = await aliceSpace.kv.get<{ from: string; message: string }>("shared/bob-was-here");
  const charlieResponse = await aliceSpace.kv.get<{ from: string; message: string }>("shared/charlie-was-here");

  if (bobResponse.ok && bobResponse.data?.data) {
    console.log(`[Alice] From Bob: "${bobResponse.data.data.message}"`);
  }
  if (charlieResponse.ok && charlieResponse.data?.data) {
    console.log(`[Alice] From Charlie: "${charlieResponse.data.data.message}"`);
  }
  console.log();

  // =========================================================================
  // PART 3: Sharing Links (Skipped - Space API not yet implemented)
  // =========================================================================
  console.log();
  console.log("=".repeat(70));
  console.log("PART 3: Sharing Links (Space API not yet implemented on server)");
  console.log("=".repeat(70));
  console.log();

  // NOTE: space.sharing.generate() and space.sharing.list() require server-side
  // support for tinycloud.share/* capabilities which are not yet implemented.
  console.log("[Alice] Sharing link generation via Space API skipped (server not yet implemented)");
  console.log();

  // =========================================================================
  // PART 4: Space Management (Skipped - Space API not yet implemented)
  // =========================================================================
  console.log();
  console.log("=".repeat(70));
  console.log("PART 4: Space Management (Space API not yet implemented on server)");
  console.log("=".repeat(70));
  console.log();

  // NOTE: spaces.list() and space.info() require server-side support for
  // tinycloud.space/* capabilities which are not yet implemented.
  console.log("[Alice] Space listing and info via Space API skipped (server not yet implemented)");
  console.log();

  // =========================================================================
  // Summary
  // =========================================================================
  console.log();
  console.log("=".repeat(70));
  console.log("Demo Complete!");
  console.log("=".repeat(70));
  console.log();
  console.log("What was demonstrated:");
  console.log();
  console.log("PART 1 - Space API Basic Operations:");
  console.log("  ✓ Got space using spaces.get('default')");
  console.log("  ✓ Stored data using space.kv.put()");
  console.log("  ✓ Used prefix scoping with space.kv.withPrefix()");
  console.log();
  console.log("PART 2 - Delegations:");
  console.log("  ✓ Created delegation using TinyCloudNode.createDelegation()");
  console.log("  ✓ Bob accessed Alice's space via useDelegation()");
  console.log("  ✓ Bob created sub-delegation for Charlie");
  console.log("  ✓ Charlie wrote via delegation chain");
  console.log();
  console.log("PART 3 - Sharing Links:");
  console.log("  ⏳ Skipped (server-side tinycloud.share/* not yet implemented)");
  console.log();
  console.log("PART 4 - Space Management:");
  console.log("  ⏳ Skipped (server-side tinycloud.space/* not yet implemented)");
  console.log();
  console.log("Working APIs Used:");
  console.log("  • spaces.get(name) - Get Space object");
  console.log("  • space.kv.put/get/list - Space-scoped KV operations");
  console.log("  • space.kv.withPrefix() - Prefix-scoped KV");
  console.log("  • TinyCloudNode.createDelegation() - Create delegation");
  console.log("  • TinyCloudNode.useDelegation() - Use received delegation");
  console.log("  • TinyCloudNode.createSubDelegation() - Create sub-delegation");
  console.log();
  console.log("Not Yet Implemented on Server:");
  console.log("  • space.delegations.create/list/revoke (needs tinycloud.delegation/*)");
  console.log("  • space.sharing.generate/list/revoke (needs tinycloud.share/*)");
  console.log("  • spaces.list(), space.info() (needs tinycloud.space/*)");
  console.log();
}

// Run the demo
runDemo().catch((error) => {
  console.error();
  console.error("Demo Failed!");
  console.error("Error:", error.message);
  console.error();
  console.error("Make sure the TinyCloud server is running at:", TINYCLOUD_URL);
  console.error("  cd repositories/tinycloud-node && cargo run");
  console.error();
  process.exit(1);
});
