#!/usr/bin/env bun
/**
 * TinyCloud Node.js SDK Demo - Delegation Chain
 *
 * Demonstrates the full TinyCloud delegation chain:
 * 1. Alice creates a namespace and stores data
 * 2. Alice delegates access to Bob (with sub-delegation enabled)
 * 3. Bob reads Alice's data and writes a response
 * 4. Bob sub-delegates access to Charlie
 * 5. Charlie writes to Alice's namespace via the delegation chain
 * 6. Alice reads messages from both Bob and Charlie
 *
 * Prerequisites:
 * - A running TinyCloud server (default: http://localhost:8000)
 *
 * Environment Variables (auto-generated if missing):
 *   TINYCLOUD_URL         - TinyCloud server URL (default: http://localhost:8000)
 *   ALICE_PRIVATE_KEY     - Alice's Ethereum private key (hex string, no 0x)
 *   BOB_PRIVATE_KEY       - Bob's Ethereum private key (hex string, no 0x)
 *   CHARLIE_PRIVATE_KEY   - Charlie's Ethereum private key (hex string, no 0x)
 *
 * Usage:
 *   bun run demo
 */

import {
  TinyCloudNode,
  serializeDelegation,
  deserializeDelegation,
} from "@tinycloudlabs/node-sdk";
import { Wallet } from "ethers";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

// ============================================================================
// Configuration
// ============================================================================

const TINYCLOUD_URL = process.env.TINYCLOUD_URL || "http://localhost:8000";
const ENV_PATH = join(import.meta.dir, "..", ".env");

// ============================================================================
// Key Management
// ============================================================================

interface UserKeys {
  alice: string;
  bob: string;
  charlie: string;
}

function generateKey(): string {
  const wallet = Wallet.createRandom();
  return wallet.privateKey.slice(2); // Remove 0x prefix
}

function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const match = trimmed.match(/^([A-Z_]+)=(.*)$/);
      if (match) {
        result[match[1]] = match[2];
      }
    }
  }
  return result;
}

function ensureKeys(): UserKeys {
  let aliceKey = process.env.ALICE_PRIVATE_KEY;
  let bobKey = process.env.BOB_PRIVATE_KEY;
  let charlieKey = process.env.CHARLIE_PRIVATE_KEY;
  let needsWrite = false;

  // Load existing .env file
  if (existsSync(ENV_PATH)) {
    const parsed = parseEnvFile(readFileSync(ENV_PATH, "utf-8"));
    aliceKey = aliceKey || parsed.ALICE_PRIVATE_KEY;
    bobKey = bobKey || parsed.BOB_PRIVATE_KEY;
    charlieKey = charlieKey || parsed.CHARLIE_PRIVATE_KEY;
  }

  // Generate missing keys
  if (!aliceKey) {
    aliceKey = generateKey();
    console.log(`[KeyGen] Generated Alice's key: ${new Wallet(`0x${aliceKey}`).address}`);
    needsWrite = true;
  }
  if (!bobKey) {
    bobKey = generateKey();
    console.log(`[KeyGen] Generated Bob's key: ${new Wallet(`0x${bobKey}`).address}`);
    needsWrite = true;
  }
  if (!charlieKey) {
    charlieKey = generateKey();
    console.log(`[KeyGen] Generated Charlie's key: ${new Wallet(`0x${charlieKey}`).address}`);
    needsWrite = true;
  }

  // Write keys to .env
  if (needsWrite) {
    const content = `# TinyCloud Demo Environment
# Auto-generated by demo.ts

TINYCLOUD_URL=http://localhost:8000

ALICE_PRIVATE_KEY=${aliceKey}
# Alice's address: ${new Wallet(`0x${aliceKey}`).address}

BOB_PRIVATE_KEY=${bobKey}
# Bob's address: ${new Wallet(`0x${bobKey}`).address}

CHARLIE_PRIVATE_KEY=${charlieKey}
# Charlie's address: ${new Wallet(`0x${charlieKey}`).address}
`;
    writeFileSync(ENV_PATH, content);
    console.log(`[KeyGen] Keys saved to ${ENV_PATH}`);
  }

  return { alice: aliceKey, bob: bobKey, charlie: charlieKey };
}

// ============================================================================
// Demo Flow
// ============================================================================

async function runDemo() {
  console.log();
  console.log("TinyCloud Node.js SDK Demo - Delegation Chain");
  console.log("=".repeat(50));
  console.log(`Server: ${TINYCLOUD_URL}`);
  console.log();

  // Step 1: Ensure keys exist
  const keys = ensureKeys();

  // Step 2: Create TinyCloudNode instances for each user
  const alice = new TinyCloudNode({
    privateKey: keys.alice,
    host: TINYCLOUD_URL,
    prefix: "demo-alice",
    autoCreateNamespace: true,
  });

  const bob = new TinyCloudNode({
    privateKey: keys.bob,
    host: TINYCLOUD_URL,
    prefix: "demo-bob",
  });

  const charlie = new TinyCloudNode({
    privateKey: keys.charlie,
    host: TINYCLOUD_URL,
    prefix: "demo-charlie",
  });

  // Step 3: All users sign in (creates their namespaces)
  console.log("[Alice] Signing in...");
  await alice.signIn();
  console.log(`[Alice] Namespace: ${alice.namespaceId}`);

  console.log("[Bob] Signing in...");
  await bob.signIn();
  console.log(`[Bob] Namespace: ${bob.namespaceId}`);

  console.log("[Charlie] Signing in...");
  await charlie.signIn();
  console.log(`[Charlie] Namespace: ${charlie.namespaceId}`);
  console.log();

  // Step 4: Alice stores data in her namespace
  console.log("[Alice] Storing greeting...");
  await alice.kv.put("shared/greeting", {
    message: "Hello from Alice!",
    timestamp: new Date().toISOString(),
  });
  console.log("[Alice] Data stored at 'shared/greeting'");
  console.log();

  // Step 5: Alice creates delegation for Bob (sub-delegation allowed by default)
  // Note: Use pkhDid (not did) for user-to-user delegations
  console.log("[Alice] Creating delegation for Bob...");
  const delegationForBob = await alice.createDelegation({
    path: "shared/",
    actions: ["tinycloud.kv/get", "tinycloud.kv/put"],
    delegateDID: bob.pkhDid,
  });
  console.log(`[Alice] Delegation created: ${delegationForBob.delegationCid}`);
  console.log();

  // --- TRANSPORT BOUNDARY ---
  // In a real app, Alice would send this delegation to Bob over a secure channel.
  // We simulate this by serializing and deserializing the delegation.
  const serializedForBob = serializeDelegation(delegationForBob);
  const receivedByBob = deserializeDelegation(serializedForBob);

  // Step 6: Bob uses the delegation to access Alice's namespace
  console.log("[Bob] Using delegation from Alice...");
  const bobAccessToAlice = await bob.useDelegation(receivedByBob);

  // Bob reads Alice's data
  const greetingResponse = await bobAccessToAlice.kv.get<{ message: string }>("greeting");
  console.log(`[Bob] Read from Alice: "${greetingResponse.data?.message}"`);

  // Bob writes a response
  await bobAccessToAlice.kv.put("bob-was-here", {
    from: "Bob",
    message: "Thanks for sharing, Alice!",
    timestamp: new Date().toISOString(),
  });
  console.log("[Bob] Wrote response to Alice's namespace");
  console.log();

  // Step 7: Bob creates sub-delegation for Charlie
  // Note: Use pkhDid (not did) for user-to-user delegations
  console.log("[Bob] Creating sub-delegation for Charlie...");
  const delegationForCharlie = await bob.createSubDelegation(receivedByBob, {
    path: "shared/",
    actions: ["tinycloud.kv/put"],
    delegateDID: charlie.pkhDid,
  });
  console.log(`[Bob] Sub-delegation created: ${delegationForCharlie.delegationCid}`);
  console.log();

  // --- TRANSPORT BOUNDARY ---
  // Bob sends the sub-delegation to Charlie
  const serializedForCharlie = serializeDelegation(delegationForCharlie);
  const receivedByCharlie = deserializeDelegation(serializedForCharlie);

  // Step 8: Charlie uses the delegation chain to write to Alice's namespace
  console.log("[Charlie] Using delegation chain...");
  const charlieAccessToAlice = await charlie.useDelegation(receivedByCharlie);

  await charlieAccessToAlice.kv.put("charlie-was-here", {
    from: "Charlie",
    message: "Hello from the end of the chain!",
    timestamp: new Date().toISOString(),
  });
  console.log("[Charlie] Wrote to Alice's namespace via delegation chain");
  console.log();

  // Step 9: Alice reads messages from both Bob and Charlie
  console.log("[Alice] Reading responses...");
  const bobResponse = await alice.kv.get<{ from: string; message: string }>("shared/bob-was-here");
  const charlieResponse = await alice.kv.get<{ from: string; message: string }>("shared/charlie-was-here");
  console.log(`[Alice] From Bob: "${bobResponse.data?.message}"`);
  console.log(`[Alice] From Charlie: "${charlieResponse.data?.message}"`);
  console.log();

  // Summary
  console.log("=".repeat(50));
  console.log("Demo Complete!");
  console.log();
  console.log("What happened:");
  console.log("  1. Alice, Bob, and Charlie each signed in (created namespaces)");
  console.log("  2. Alice stored data and delegated access to Bob");
  console.log("  3. Bob read Alice's data and wrote a response");
  console.log("  4. Bob sub-delegated write access to Charlie");
  console.log("  5. Charlie wrote to Alice's namespace via the chain");
  console.log("  6. Alice read messages from both Bob and Charlie");
  console.log();
}

// Run the demo
runDemo().catch((error) => {
  console.error();
  console.error("Demo Failed!");
  console.error("Error:", error.message);
  console.error();
  console.error("Make sure the TinyCloud server is running at:", TINYCLOUD_URL);
  console.error("  cd repositories/tinycloud-node && cargo run");
  console.error();
  process.exit(1);
});
