#!/usr/bin/env bun
/**
 * TinyCloud ETH Key Generator
 *
 * Generates Ethereum private keys for Alice and Bob and outputs
 * them in .env format. Run this once to set up demo environment.
 *
 * Usage:
 *   bun run generate-keys              # Generate keys and print to stdout
 *   bun run generate-keys --write      # Write to .env file
 */

import { Wallet } from "ethers";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ENV_PATH = join(import.meta.dir, "..", ".env");

interface KeyPair {
  name: string;
  privateKey: string;
  address: string;
}

function generateKey(name: string): KeyPair {
  const wallet = Wallet.createRandom();
  return {
    name,
    privateKey: wallet.privateKey.slice(2), // Remove 0x prefix
    address: wallet.address,
  };
}

function formatEnvContent(alice: KeyPair, bob: KeyPair): string {
  return `# TinyCloud Demo Environment
# Generated by: bun run generate-keys

# TinyCloud server URL
TINYCLOUD_URL=http://localhost:8000

# Alice's Ethereum private key (without 0x prefix)
ALICE_PRIVATE_KEY=${alice.privateKey}
# Alice's address: ${alice.address}

# Bob's Ethereum private key (without 0x prefix)
BOB_PRIVATE_KEY=${bob.privateKey}
# Bob's address: ${bob.address}
`;
}

function main() {
  const shouldWrite = process.argv.includes("--write");

  // Check if .env already exists with keys
  if (existsSync(ENV_PATH)) {
    const existing = readFileSync(ENV_PATH, "utf-8");
    if (existing.includes("ALICE_PRIVATE_KEY") && existing.includes("BOB_PRIVATE_KEY")) {
      console.log("Keys already exist in .env file.");
      console.log(`Location: ${ENV_PATH}`);
      console.log();
      console.log("To regenerate, delete the .env file first or remove the existing keys.");
      return;
    }
  }

  console.log("=".repeat(60));
  console.log("TinyCloud ETH Key Generator");
  console.log("=".repeat(60));
  console.log();

  const alice = generateKey("Alice");
  const bob = generateKey("Bob");

  console.log("Generated keys:");
  console.log();
  console.log(`Alice:`);
  console.log(`  Address:     ${alice.address}`);
  console.log(`  Private Key: ${alice.privateKey}`);
  console.log();
  console.log(`Bob:`);
  console.log(`  Address:     ${bob.address}`);
  console.log(`  Private Key: ${bob.privateKey}`);
  console.log();

  const envContent = formatEnvContent(alice, bob);

  if (shouldWrite) {
    writeFileSync(ENV_PATH, envContent);
    console.log(`Written to: ${ENV_PATH}`);
  } else {
    console.log("-".repeat(60));
    console.log(".env content:");
    console.log("-".repeat(60));
    console.log(envContent);
    console.log("-".repeat(60));
    console.log();
    console.log("To write to .env file, run:");
    console.log("  bun run generate-keys --write");
  }
}

main();
