export { DEFAULT_MAX_CONTENT_BLOB_BYTES, DEFAULT_MAX_SEALED_BLOB_BYTES, SHARE_RESULT_VERSION, inspectShare, receiveShare, ShareReceiveError, toShareErrorInfo, type ShareReceiveAuthorizationRequired, type ShareErrorCode, type ShareErrorInfo, type ShareFetchOptions, type ShareInspection, type ShareMetadata, type ShareReceiveOutcome, type ShareReceiveResult } from "./receive.js";
export { DEFAULT_SHARE_LIFETIME_MS, SHARE_CONTENT_LIMIT, SHARE_PUBLISH_RESULT_VERSION, redactPublishedShare, SharePublishError, type PublishedShare, type PublishedShareDeliveryMaterial, type PublishedShareMetadata, type SharePublishErrorCode, type SharePublishOptions, type SharePublishTarget } from "./publish.js";
export { parseAddressedEnvelope, type ParsedAddressedEnvelope } from "./addressed.js";
export { publishAddressedShare } from "./addressed-publish.js";
export type { AddressedOwnerRootInput, AddressedOwnerRootReceipt, AddressedPolicyRegistrationInput, AddressedPolicyRegistrationReceipt, AddressedPublishAuthority, AddressedSharePublishOptions } from "./addressed-publish.js";
export { checkBearerDelegation, resourceUriCovers, requiredResourceUri, type CheckBearerDelegationOptions, type DelegationCheckResult } from "@tinycloud/share-envelope";
export { canonicalize, fromBase64Url, toBase64Url } from "@tinycloud/share-envelope";
export { MemoryShareCache } from "./cache.js";
export type { ShareCache, ShareCacheEntry, ShareCacheKey, ShareCacheMetadata } from "./cache.js";
export { createDelegatedShareKey, restoreDelegatedShareKey, createPolicyEnforcementDelegation, canonicalOwnerSharePolicy, computeOwnerShareRegistrationCid, validateOwnerSharePolicyRegistration, validateOwnerSharePolicyRegistrationBytes, OWNER_SHARE_REGISTRATION_DOMAIN, MAX_CONTENT_BYTES } from "./owner-policy.js";
export type { OwnerDelegationReceipt, OwnerDelegationPermission, CreateOwnerDelegationParams, OwnerShareAction, OwnerShareDecryption, OwnerShareMatcher, OwnerSharePolicyV2, DelegatedShareKey, SignedDelegation, RegisterOwnerSharePolicyParams, OwnerSharePolicyRegistration, OwnerSharePolicyRegistrationReceipt } from "./owner-policy.js";
export { MemorySenderShareRecordStorage, MemorySenderShareKeyStorage, SenderShareStore, historyRecordForPublishedShare } from "./history.js";
export { MemoryEncryptedShareHistoryStorage, EncryptedSenderShareHistory } from "./history.js";
export type { SenderShareRecord, SenderShareRecordStorage, SenderShareKeyStorage, SenderShareRevocationScope, EncryptedShareHistoryStorage } from "./history.js";
export { authorizeShare, authorizationMethodForTarget } from "./authorization.js";
export type { ShareAuthorizationMethod, ShareAuthorizationRequired, ShareAuthorizationDenied, ShareAuthorizationReady, ShareAuthorizationResult, ShareAuthorizationAdapter, ShareAuthorizedContent } from "./authorization.js";
export { notifyShare, recipientMatchesShareRecord, ShareNotifyError } from "./notify.js";
export type { ShareNotifyState, ShareNotifyResult, ShareNotifyInput, ShareDeliveryAdapter } from "./notify.js";
export { listShares, showShare, revokeShare } from "./lifecycle.js";
export type { ShareHistoryView, ShareRevocationResult, ShareRevocationAdapter } from "./lifecycle.js";
export { normalizeShareTarget, publishTargetShare, targetAuthorizationMethod } from "./targets.js";
export type { ShareTarget, TargetPublishInput, TargetPublishOutcome, TargetPublishAdapter } from "./targets.js";
export { ShareRecipientClient, createAddressedAuthorization } from "./recipient.js";
export type { ShareNodeTrust, SharePolicyChallenge, SharePresentationMaterial, ShareRecipientClientOptions, SharePolicySession } from "./recipient.js";
export { SHARE_V2_PROTOCOL, createShareV2HolderBindingArtifact } from "./protocol.js";
export { publishPolicyShare, claimShare, resumeShareAuthorization } from "./policy.js";
export type { SharePolicyPublishAdapter } from "./policy.js";
export { NATIVE_SHARE_FRAGMENT_PARAMETER, createNativeShare, openNativeShare, parseNativeShareUrl } from "./native.js";
export type { NativeSharingService } from "./native.js";
