[package]
name = "tinycloud-web-sdk-rs"
version = "0.1.0"
authors = ["TinyCloud, Inc."]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Library for use in tinycloud-web-sdk."
repository = "https://github.com/tinycloudlabs/web-sdk/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
siwe-recap = "0.1.0"
did-method-key = "0.2.1"
console_error_panic_hook = "0.1"
rand = { version = "0.7", features = ["wasm-bindgen"] }
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4.3"
iri-string = "0.6.0"
js-sys = "0.3.59"
kepler-sdk = { git = "https://github.com/tinycloudlabs/kepler" }
kepler-sdk-wasm = { git = "https://github.com/tinycloudlabs/kepler" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.83"
serde-wasm-bindgen = "0.4"
siwe = "0.5"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.32"
web-sys = { version = "0.3.59", features = ["console"] }

[dependencies.ssi]
version = "0.6"
features = ["ed25519"]
default-features = false

[dev-dependencies]
tokio = { version = "1", features = ["full"] }