name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run only (no actual publish)'
        type: boolean
        default: false

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Set npm registry
        if: ${{ !inputs.dryRun }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          bun run npm-pub

      - name: Publish (dry run)
        if: ${{ inputs.dryRun }}
        run: bun changeset publish --access public --dry-run

      - name: Publish
        if: ${{ !inputs.dryRun }}
        run: bun changeset publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tags
        if: ${{ !inputs.dryRun }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          ROOT_DIR=$(pwd)
          
          cd "$ROOT_DIR/packages/web-core"
          CORE_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          git tag "web-core-v$CORE_VERSION"
          
          cd "$ROOT_DIR/packages/web-sdk-rs"
          SDK_RS_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          git tag "web-sdk-rs-v$SDK_RS_VERSION"
          
          cd "$ROOT_DIR/packages/web-sdk"
          SDK_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          git tag "web-sdk-v$SDK_VERSION"
          
          cd "$ROOT_DIR"
          git push origin --tags